def invoice_response():
    return {
        "id": "5efd97830425db620ec35e22",
        "external_id": "invoice-1593677698",
        "user_id": "5ed75086a883856178afc12e",
        "status": "PENDING",
        "merchant_name": "Xendit&amp;#x27;s Intern",
        "merchant_profile_picture_url": "https://xnd-companies.s3.amazonaws.com/prod/1591169469152_279.png",
        "amount": 20000,
        "payer_email": "customer@domain.com",
        "description": "Invoice Demo #123",
        "expiry_date": "2020-07-03T08:14:59.379Z",
        "invoice_url": "https://invoice-staging.xendit.co/web/invoices/5efd97830425db620ec35e22",
        "available_banks": [
            {
                "bank_code": "MANDIRI",
                "collection_type": "POOL",
                "bank_account_number": "8860846849727",
                "transfer_amount": 20000,
                "bank_branch": "Virtual Account",
                "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                "identity_amount": 0,
            },
            {
                "bank_code": "BRI",
                "collection_type": "POOL",
                "bank_account_number": "2621554802920",
                "transfer_amount": 20000,
                "bank_branch": "Virtual Account",
                "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                "identity_amount": 0,
            },
            {
                "bank_code": "BNI",
                "collection_type": "POOL",
                "bank_account_number": "880854592871",
                "transfer_amount": 20000,
                "bank_branch": "Virtual Account",
                "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                "identity_amount": 0,
            },
            {
                "bank_code": "PERMATA",
                "collection_type": "POOL",
                "bank_account_number": "821456655233",
                "transfer_amount": 20000,
                "bank_branch": "Virtual Account",
                "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                "identity_amount": 0,
            },
            {
                "bank_code": "BCA",
                "collection_type": "POOL",
                "bank_account_number": "1076619840767",
                "transfer_amount": 20000,
                "bank_branch": "Virtual Account",
                "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                "identity_amount": 0,
            },
        ],
        "available_retail_outlets": [
            {
                "retail_outlet_name": "ALFAMART",
                "payment_code": "TEST35284",
                "transfer_amount": 1000000,
            }
        ],
        "available_ewallets": [],
        "should_exclude_credit_card": False,
        "should_send_email": False,
        "created": "2020-07-02T08:14:59.460Z",
        "updated": "2020-07-02T08:14:59.460Z",
        "currency": "IDR",
    }


def multiple_invoice_response():
    return [
        {
            "id": "5efdb0210425db620ec35fb3",
            "external_id": "invoice-1593684000",
            "user_id": "5ed75086a883856178afc12e",
            "status": "PENDING",
            "merchant_name": "Xendit&amp;#x27;s Intern",
            "merchant_profile_picture_url": "https://xnd-companies.s3.amazonaws.com/prod/1591169469152_279.png",
            "amount": 20000,
            "payer_email": "customer@domain.com",
            "description": "Invoice Demo #123",
            "expiry_date": "2020-07-03T10:00:01.148Z",
            "invoice_url": "https://invoice-staging.xendit.co/web/invoices/5efdb0210425db620ec35fb3",
            "available_banks": [
                {
                    "bank_code": "MANDIRI",
                    "collection_type": "POOL",
                    "bank_account_number": "8860846854335",
                    "transfer_amount": 20000,
                    "bank_branch": "Virtual Account",
                    "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                    "identity_amount": 0,
                },
                {
                    "bank_code": "BRI",
                    "collection_type": "POOL",
                    "bank_account_number": "2621554807492",
                    "transfer_amount": 20000,
                    "bank_branch": "Virtual Account",
                    "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                    "identity_amount": 0,
                },
                {
                    "bank_code": "BNI",
                    "collection_type": "POOL",
                    "bank_account_number": "880854597383",
                    "transfer_amount": 20000,
                    "bank_branch": "Virtual Account",
                    "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                    "identity_amount": 0,
                },
                {
                    "bank_code": "PERMATA",
                    "collection_type": "POOL",
                    "bank_account_number": "821456659745",
                    "transfer_amount": 20000,
                    "bank_branch": "Virtual Account",
                    "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                    "identity_amount": 0,
                },
                {
                    "bank_code": "BCA",
                    "collection_type": "POOL",
                    "bank_account_number": "1076619844859",
                    "transfer_amount": 20000,
                    "bank_branch": "Virtual Account",
                    "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                    "identity_amount": 0,
                },
            ],
            "available_retail_outlets": [
                {
                    "retail_outlet_name": "ALFAMART",
                    "payment_code": "TEST34956",
                    "transfer_amount": 20000,
                }
            ],
            "available_ewallets": [],
            "should_exclude_credit_card": False,
            "should_send_email": False,
            "created": "2020-07-02T10:00:01.285Z",
            "updated": "2020-07-02T10:00:01.285Z",
            "currency": "IDR",
        },
        {
            "id": "5efdaaf10425db620ec35f68",
            "external_id": "invoice-1593682673",
            "user_id": "5ed75086a883856178afc12e",
            "status": "PENDING",
            "merchant_name": "Xendit&amp;#x27;s Intern",
            "merchant_profile_picture_url": "https://xnd-companies.s3.amazonaws.com/prod/1591169469152_279.png",
            "amount": 1000000,
            "payer_email": "customer@domain.com",
            "description": "Invoice Demo #123",
            "expiry_date": "2020-07-03T09:37:53.334Z",
            "invoice_url": "https://invoice-staging.xendit.co/web/invoices/5efdaaf10425db620ec35f68",
            "available_banks": [
                {
                    "bank_code": "MANDIRI",
                    "collection_type": "POOL",
                    "bank_account_number": "8860846853555",
                    "transfer_amount": 1000000,
                    "bank_branch": "Virtual Account",
                    "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                    "identity_amount": 0,
                },
                {
                    "bank_code": "BRI",
                    "collection_type": "POOL",
                    "bank_account_number": "2621554806712",
                    "transfer_amount": 1000000,
                    "bank_branch": "Virtual Account",
                    "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                    "identity_amount": 0,
                },
                {
                    "bank_code": "BNI",
                    "collection_type": "POOL",
                    "bank_account_number": "880854596627",
                    "transfer_amount": 1000000,
                    "bank_branch": "Virtual Account",
                    "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                    "identity_amount": 0,
                },
                {
                    "bank_code": "PERMATA",
                    "collection_type": "POOL",
                    "bank_account_number": "821456659001",
                    "transfer_amount": 1000000,
                    "bank_branch": "Virtual Account",
                    "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                    "identity_amount": 0,
                },
                {
                    "bank_code": "BCA",
                    "collection_type": "POOL",
                    "bank_account_number": "1076619844115",
                    "transfer_amount": 1000000,
                    "bank_branch": "Virtual Account",
                    "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                    "identity_amount": 0,
                },
            ],
            "available_retail_outlets": [
                {
                    "retail_outlet_name": "ALFAMART",
                    "payment_code": "TEST34954",
                    "transfer_amount": 1000000,
                }
            ],
            "available_ewallets": [],
            "should_exclude_credit_card": False,
            "should_send_email": False,
            "created": "2020-07-02T09:37:53.400Z",
            "updated": "2020-07-02T09:37:53.400Z",
            "currency": "IDR",
        },
        {
            "id": "5efdaae80425db620ec35f66",
            "external_id": "invoice-1593682664",
            "user_id": "5ed75086a883856178afc12e",
            "status": "PENDING",
            "merchant_name": "Xendit&amp;#x27;s Intern",
            "merchant_profile_picture_url": "https://xnd-companies.s3.amazonaws.com/prod/1591169469152_279.png",
            "amount": 100000,
            "payer_email": "customer@domain.com",
            "description": "Invoice Demo #123",
            "expiry_date": "2020-07-03T09:37:44.451Z",
            "invoice_url": "https://invoice-staging.xendit.co/web/invoices/5efdaae80425db620ec35f66",
            "available_banks": [
                {
                    "bank_code": "MANDIRI",
                    "collection_type": "POOL",
                    "bank_account_number": "8860846853531",
                    "transfer_amount": 100000,
                    "bank_branch": "Virtual Account",
                    "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                    "identity_amount": 0,
                },
                {
                    "bank_code": "BRI",
                    "collection_type": "POOL",
                    "bank_account_number": "2621554806688",
                    "transfer_amount": 100000,
                    "bank_branch": "Virtual Account",
                    "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                    "identity_amount": 0,
                },
                {
                    "bank_code": "BNI",
                    "collection_type": "POOL",
                    "bank_account_number": "880854596603",
                    "transfer_amount": 100000,
                    "bank_branch": "Virtual Account",
                    "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                    "identity_amount": 0,
                },
                {
                    "bank_code": "PERMATA",
                    "collection_type": "POOL",
                    "bank_account_number": "821456658977",
                    "transfer_amount": 100000,
                    "bank_branch": "Virtual Account",
                    "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                    "identity_amount": 0,
                },
                {
                    "bank_code": "BCA",
                    "collection_type": "POOL",
                    "bank_account_number": "1076619844091",
                    "transfer_amount": 100000,
                    "bank_branch": "Virtual Account",
                    "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                    "identity_amount": 0,
                },
            ],
            "available_retail_outlets": [
                {
                    "retail_outlet_name": "ALFAMART",
                    "payment_code": "TEST34953",
                    "transfer_amount": 100000,
                }
            ],
            "available_ewallets": [],
            "should_exclude_credit_card": False,
            "should_send_email": False,
            "created": "2020-07-02T09:37:44.511Z",
            "updated": "2020-07-02T09:37:44.511Z",
            "currency": "IDR",
        },
    ]
