def invoice_response():
    return {
        "id": "5efd97830425db620ec35e22",
        "external_id": "invoice-1593677698",
        "user_id": "5ed75086a883856178afc12e",
        "status": "PENDING",
        "merchant_name": "Xendit&amp;#x27;s Intern",
        "merchant_profile_picture_url": "https://xnd-companies.s3.amazonaws.com/prod/1591169469152_279.png",
        "amount": 20000,
        "payer_email": "customer@domain.com",
        "description": "Invoice Demo #123",
        "expiry_date": "2020-07-03T08:14:59.379Z",
        "invoice_url": "https://invoice-staging.xendit.co/web/invoices/5efd97830425db620ec35e22",
        "available_banks": [
            {
                "bank_code": "MANDIRI",
                "collection_type": "POOL",
                "bank_account_number": "8860846849727",
                "transfer_amount": 20000,
                "bank_branch": "Virtual Account",
                "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                "identity_amount": 0,
            },
            {
                "bank_code": "BRI",
                "collection_type": "POOL",
                "bank_account_number": "2621554802920",
                "transfer_amount": 20000,
                "bank_branch": "Virtual Account",
                "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                "identity_amount": 0,
            },
            {
                "bank_code": "BNI",
                "collection_type": "POOL",
                "bank_account_number": "880854592871",
                "transfer_amount": 20000,
                "bank_branch": "Virtual Account",
                "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                "identity_amount": 0,
            },
            {
                "bank_code": "PERMATA",
                "collection_type": "POOL",
                "bank_account_number": "821456655233",
                "transfer_amount": 20000,
                "bank_branch": "Virtual Account",
                "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                "identity_amount": 0,
            },
            {
                "bank_code": "BCA",
                "collection_type": "POOL",
                "bank_account_number": "1076619840767",
                "transfer_amount": 20000,
                "bank_branch": "Virtual Account",
                "account_holder_name": "XENDIT&AMP;#X27;S INTERN",
                "identity_amount": 0,
            },
        ],
        "available_ewallets": [],
        "should_exclude_credit_card": False,
        "should_send_email": False,
        "created": "2020-07-02T08:14:59.460Z",
        "updated": "2020-07-02T08:14:59.460Z",
        "currency": "IDR",
    }
